### ISSUE TITLE
Release v3.0.0

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/twig-i18n-extension#3]
CI: https://travis-ci.com/github/phpmyadmin/twig-i18n-extension/builds/171226555 (passing)
Pull-requests:
- #1 
- #2 

Commits:
- Add project history (a8a34bde42cb8ece7dd329f4ce6a22af7eab0eac)
- Add support for Twig v3 (7b60d07f8fe1d528840e70101f1b4dcd852a033f)
- Add a .gitattributes file (c72fe752610b127650f0aa5a545ae064eb220919)
- Merge #2 - support Twig 3 (12a5e3961c4d66e975f113a0c14ef785139d167e)
- Remove extra field from composer.json (b1c5492ae5e67d90f737bd576a9e885bffede3f6)
- Require php >= 7.1 (2a28466fe0e94603860d25509aac15dc5f1916fb)
- Update TravisCI matrix and remove deprecated config (e9b321d71525ed54584fedc24395382fcbfbf4e0)
- improve README.rst (ccb70f06fd2ad8cd1fb3737a65b6f0796984d1cb)
- Require phpunit/phpunit 8 or 9 (7c00896d8724b3915ecab635d4cfb18b522cba13)
- Remove phpunit bridge (2ea9270cae31b499e9dbe76b1d51e9170fde8e22)
- Update test commands (9f31190e90616bf8aa1b4b382c73d89fc0e36b1e)
- Set up phpmyadmin/coding-standard (e28026d1d5c5eead03a3ad300dd4523d8b9c7fa7)
- Apply phpmyadmin/coding-standard (64298e21d0ff9dc5e5c545442fe71655311393c5)
- Import upstream changes for php 8 compatibility (8cc1817ba8abdbf1612249c19a5bbb28173b8de5)
- Add a CHANGELOG.md file (905ba825b4890ef26147a9a5f7a50a2bce8a96d2)
- Add PHP nightly to TravisCI matrix (4fe2ac3be46eeca8d4f7c0a8c7c14d5a163c792b)
- Skip xdebug for PHP 8.0 (f2efeb68b68fc33d2f9b8faf9d2b9f44cdbbd976)
- Merge #1 - Add project history (3570795c095b599a3236d339a041c355701c9d71)
- Allow phpunit 7 (04a4b350083580942d33df74145a56c66152ec54)
- Fix RST code block (a6204d0d4497f9924bbfe198e7ce16ccbc2ed536)
- Add a documentation php code block (9cfdd50ca9d7e04aea540bf3aeba402cc5cd8fea)
- Add a php doc block and switch jinja to twig (f7d5d75d3f56197e00015330833694ba2c3a3060)

**Comment by williamdes** [comment]
@ibennetch or @mauriciofauth could someone confirm that I can create the release tag for the above changes and the [CHANGELOG](https://github.com/phpmyadmin/twig-i18n-extension/blob/master/CHANGELOG.md) ?

**Comment by williamdes** [comment]
Since we will be dropping php versions, should it be 3.0.0 ?

**Comment by ibennetch** [comment]
Looks good to me.

I would lean towards 3.0.0 because of the major change with required PHP versions.

**Comment by williamdes** [comment]
Thank you for the quick response, after @mauriciofauth agrees:
- I will tag v3.0.0 and write a release
- Upgrade the package in phpmyadmin/phpmyadmin
- Import the version in https://salsa.debian.org/phpmyadmin-team/twig-i18n-extension


NB: since approval I added:
- Import some upstream changes to TransNode class (94529848cca874b866e9f8f8463bae26d6bab2a1)
- Add some phpdoc blocks (335e70954abbbc207cf2d1d41b3f937c4cfb51f5)

**Comment by mauriciofauth** [comment]
Looks good to me.

**Comment by williamdes** [comment]
Done: https://github.com/phpmyadmin/twig-i18n-extension/releases

Added:
- Add support and config in composer.json and sort require-dev (db24b5d57f23dbac9aa6e8bf727ea0712e170200)
- Exclude phpcs.xml.dist from dist version (c71911f888c73341b1793bac8b6c9e513ff3182b)
