### ISSUE TITLE
The trans twig filter generates non translatable code

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/twig-i18n-extension#7]
The trans filter generates code which gettext fails to extract and thus such strings are no longer translatable.

I've noticed it on following code, but it might happen in more cases:

https://github.com/phpmyadmin/phpmyadmin/blob/5acd64f84d964e5f2db6170ecb5a42581e74ca12/templates/columns_definitions/table_fields_definitions.twig#L27-L30

This generates:

```php
        echo PhpMyAdmin\Util::showHint(_gettext(("For default values, please enter just a single value, without" . " backslash escaping or quotes, using this format: a")));
```

The problem here is string concatenation as xgettext doesn't deal with that.

**Comment by drjayvee** [comment]
I just happen to drive by here and agree with @mauriciofauth.

I'd suggest not fixing this and closing this issue.
